export type Lang = "en" | "hi";

export const UI_STRINGS = {
  "scope.india": { en: "India", hi: "भारत" },
  "scope.india-abroad": { en: "India Abroad", hi: "विदेश में भारत" },
  "scope.impact-on-india": { en: "Impact on India", hi: "भारत पर असर" },
  "scope.world": { en: "World", hi: "विश्व" },
  "scope.for-you": { en: "For You", hi: "आपके लिए" },

  "category.all": { en: "All", hi: "सभी" },
  "category.finance": { en: "Finance", hi: "फाइनेंस" },
  "category.politics": { en: "Politics", hi: "राजनीति" },
  "category.sports": { en: "Sports", hi: "खेल" },
  "category.technology": { en: "Technology", hi: "टेक्नोलॉजी" },
  "category.business-economy": { en: "Business & Economy", hi: "बिज़नेस" },
  "category.environment": { en: "Environment", hi: "पर्यावरण" },
  "category.education": { en: "Education", hi: "शिक्षा" },
  "category.entertainment": { en: "Entertainment", hi: "मनोरंजन" },
  "category.health": { en: "Health", hi: "स्वास्थ्य" },
  "category.gen-z": { en: "Gen-Z", hi: "जेन-ज़ी" },
  "category.general": { en: "General", hi: "सामान्य" },

  "sort.newest": { en: "Newest", hi: "सबसे नए" },
  "sort.trending": { en: "Today's Top", hi: "आज की टॉप खबरें" },
  "sort.popular": { en: "Most Popular", hi: "सबसे पॉपुलर" },
  "sort.oldest": { en: "Oldest", hi: "सबसे पुराने" },

  "range.live": { en: "Live", hi: "लाइव" },
  "range.1d": { en: "1 Day", hi: "1 दिन" },
  "range.week": { en: "This Week", hi: "इस सप्ताह" },
  "range.month": { en: "This Month", hi: "इस महीने" },
  "range.past-month": { en: "Past Month", hi: "पिछला महीना" },
  "range.year": { en: "Past Year", hi: "पिछला वर्ष" },

  "action.save": { en: "Save", hi: "सेव करें" },
  "action.readOriginal": { en: "Read in full", hi: "पूरा पढ़ें" },
  "action.compareCoverage": { en: "Compare coverage", hi: "कवरेज की तुलना करें" },
  "action.alsoReportedBy": { en: "Also reported by", hi: "इनके द्वारा भी रिपोर्ट किया गया" },
  "state.opinion": { en: "Opinion/Analysis", hi: "राय/विश्लेषण" },
  "state.newsReport": { en: "News Report", hi: "समाचार रिपोर्ट" },
  "state.headlineOnly": { en: "No summary for this one. Read the original for the full story.", hi: "इस खबर का सार नहीं है। पूरी खबर सोर्स पर पढ़ें।" },
  "state.forYouNoPrefs": { en: "Pick a few categories in Preferences to fill this feed.", hi: "यह फ़ीड भरने के लिए प्राथमिकताओं में कुछ श्रेणियाँ चुनें।" },
  "state.emptyWiden": { en: "Look further back", hi: "और पीछे तक देखें" },
  "state.emptyClearCategory": { en: "Show all categories", hi: "सभी श्रेणियाँ दिखाएँ" },
  "state.emptyClearDay": { en: "Show the whole month", hi: "पूरा महीना दिखाएँ" },
  "state.empty": { en: "Nothing here for these filters.", hi: "इन फ़िल्टर में कुछ नहीं है।" },

  "prefs.localNote": { en: "Saved in this browser only. No account, no email.", hi: "सिर्फ़ इस ब्राउज़र में सेव। कोई अकाउंट या ईमेल नहीं।" },
  "prefs.noCookie": { en: "Could not save. Enable cookies and try again.", hi: "सेव नहीं हो सका। कुकीज़ चालू करके दोबारा कोशिश करें।" },
  "prefs.title": { en: "Preferences", hi: "सेटिंग्स" },
  "prefs.categories": { en: "Categories in your For You feed", hi: "आपके लिए फ़ीड में कौन से टॉपिक?" },
  "prefs.scopes": { en: "Draw stories from these sections", hi: "इन सेक्शन से खबरें लें" },
  "prefs.scopesHint": { en: "Leave all unchecked to draw from every section.", hi: "सब खाली छोड़ें तो हर सेक्शन से आएँगी।" },
  "prefs.defaultSort": { en: "Default sort", hi: "डिफ़ॉल्ट सॉर्ट" },
  "prefs.defaultRange": { en: "Default time range", hi: "डिफ़ॉल्ट समय सीमा" },
  "prefs.save": { en: "Save preferences", hi: "सेटिंग्स सेव करें" },
  "prefs.saved": { en: "Preferences saved.", hi: "सेटिंग्स सेव हो गईं।" },

  "saved.title": { en: "Saved", hi: "सेव किए हुए" },
  "saved.active": { en: "Active", hi: "सक्रिय" },
  "saved.due": { en: "Due", hi: "पढ़ना है" },
  "saved.archived": { en: "Archived", hi: "आर्काइव" },
  "saved.all": { en: "All collections", hi: "सभी कलेक्शन" },
  "saved.collection": { en: "Collection", hi: "कलेक्शन" },
  "saved.noCollection": { en: "No collection", hi: "कोई कलेक्शन नहीं" },
  "saved.newCollection": { en: "New collection name", hi: "नए कलेक्शन का नाम" },
  "saved.createCollection": { en: "Create collection", hi: "कलेक्शन बनाएँ" },
  "saved.deleteCollection": { en: "Delete collection", hi: "कलेक्शन हटाएँ" },
  "saved.note": { en: "Note", hi: "नोट" },
  "saved.notePlaceholder": { en: "Why you saved this…", hi: "क्यों सेव किया…" },
  "saved.remindAt": { en: "Come back on", hi: "किस दिन पढ़ना है" },
  "saved.update": { en: "Update", hi: "अपडेट" },
  "saved.archive": { en: "Archive", hi: "आर्काइव करें" },
  "saved.unarchive": { en: "Unarchive", hi: "आर्काइव से निकालें" },
  "saved.remove": { en: "Remove", hi: "हटाएँ" },
  "saved.empty": { en: "Nothing here yet. Save a story from any feed.", hi: "यहाँ अभी कुछ नहीं है। किसी भी फ़ीड से खबर सेव करें।" },
  "saved.overdue": { en: "Overdue", hi: "देर हो गई" },

  "action.readHere": { en: "Read here", hi: "यहीं पढ़ें" },
  "action.like": { en: "Like", hi: "पसंद" },
  "action.liked": { en: "Liked", hi: "पसंद किया" },
  "action.interested": { en: "Interested", hi: "दिलचस्पी है" },
  "action.notInterested": { en: "Not interested", hi: "दिलचस्पी नहीं" },

  "reader.minRead": { en: "min read", hi: "मिनट का पढ़ना" },
  "reader.continueAt": { en: "Continue reading at", hi: "आगे यहाँ पढ़ें" },
  "reader.copyrightTitle": { en: "Full story not available here", hi: "पूरी खबर यहाँ नहीं दिखा सकते" },
  "reader.copyrightBody": { en: "This publisher does not allow their full article to be republished. You are reading the opening; the rest is on their site.", hi: "यह पब्लिशर अपनी पूरी खबर कहीं और छापने की इजाज़त नहीं देता। यहाँ शुरुआत है, बाकी उनकी साइट पर।" },
  "reader.noContent": { en: "We could not retrieve this article's text. Read it at the source.", hi: "इस खबर का टेक्स्ट नहीं मिल सका। सोर्स पर पढ़ें।" },
  "reader.backToFeed": { en: "Back to feed", hi: "फ़ीड पर वापस" },

  "timeline.title": { en: "Month at a glance", hi: "महीने भर की खबरें" },
  "timeline.allDays": { en: "All days", hi: "सभी दिन" },
  "timeline.bigDay": { en: "Big news day", hi: "बड़ी खबर का दिन" },
  "timeline.stories": { en: "stories", hi: "खबरें" },

  "search.placeholder": { en: "Search stories", hi: "खबरें खोजें" },
  "search.title": { en: "Search", hi: "खोज" },
  "search.submit": { en: "Search", hi: "खोजें" },
  "search.prompt": { en: "Search all sources and dates.", hi: "सभी सोर्स और तारीख़ों में खोजें।" },
  "search.noResults": { en: "Nothing matched that. Try different words.", hi: "इससे कुछ नहीं मिला। दूसरे शब्द आज़माएँ।" },
  "search.resultCount": { en: "results", hi: "नतीजे" },
  "page.more": { en: "More stories", hi: "और खबरें" },
  "page.back": { en: "Back", hi: "पीछे" },
  "page.number": { en: "Page", hi: "पेज" },

  "nav.search": { en: "Search", hi: "खोज" },

  "nav.insights": { en: "Insights", hi: "आँकड़े" },
  "nav.saved": { en: "Saved", hi: "सेव किए हुए" },
  "nav.preferences": { en: "Preferences", hi: "सेटिंग्स" },

  "action.saved": { en: "Saved", hi: "सेव किया" },

  "insights.title": { en: "Insights", hi: "आँकड़े" },
  "insights.subtitle": { en: "Who gets stories out first, who leans on the wires, and what each outlet covers.", hi: "कौन सबसे पहले खबर देता है, कौन वायर पर निर्भर है, और कौन किस विषय पर लिखता है।" },
  "insights.windowPrefix": { en: "Last", hi: "पिछले" },
  "insights.days": { en: "days", hi: "दिन" },
  "insights.empty": { en: "Not enough data for this period yet.", hi: "इस अवधि के लिए अभी पर्याप्त डेटा नहीं है।" },
  "insights.notInstalledTitle": { en: "Analytics views missing", hi: "एनालिटिक्स व्यू नहीं मिले" },
  "insights.notInstalledBody": { en: "Run this once against the database, then reload:", hi: "डेटाबेस पर यह एक बार चलाएँ, फिर पेज रीलोड करें:" },
  "insights.minSample": { en: "Outlets with fewer stories than this are left out:", hi: "इससे कम खबरों वाले सोर्स नहीं दिखाए गए:" },
  "insights.tableView": { en: "Show as table", hi: "टेबल में देखें" },
  "insights.less": { en: "Fewer", hi: "कम" },
  "insights.more": { en: "More", hi: "ज़्यादा" },
  "insights.min": { en: "min", hi: "मिनट" },
  "insights.hours": { en: "h", hi: "घंटे" },
  "insights.daysAgo": { en: "d ago", hi: "दिन पहले" },
  "insights.never": { en: "Never", hi: "कभी नहीं" },

  "insights.kpi.articles": { en: "Articles", hi: "लेख" },
  "insights.kpi.stories": { en: "Distinct stories", hi: "अलग खबरें" },
  "insights.kpi.shared": { en: "Covered by 2+ outlets", hi: "2+ सोर्स ने छापीं" },
  "insights.kpi.sources": { en: "Sources reporting", hi: "सक्रिय सोर्स" },
  "insights.kpi.usableTime": { en: "Usable publish times", hi: "सही प्रकाशन समय" },
  "insights.kpi.grounded": { en: "Summaries grounded", hi: "सत्यापित सार" },
  "insights.kpi.of": { en: "of", hi: "में से" },

  "insights.speed.title": { en: "Who's first", hi: "सबसे पहले कौन" },
  "insights.speed.body": { en: "Only stories at least two outlets ran. \"First\" is how often an outlet published before the others; delay is the median time behind whoever was first.", hi: "सिर्फ़ वे खबरें जो कम से कम दो सोर्स ने छापीं। 'पहले' यानी कितनी बार सबसे पहले छापा; देरी यानी पहले वाले से कितनी देर बाद (मीडियन)।" },
  "insights.speed.firstRate": { en: "First", hi: "पहले" },
  "insights.speed.medianLag": { en: "Median delay", hi: "देरी (मीडियन)" },
  "insights.speed.stories": { en: "Stories", hi: "खबरें" },

  "insights.wire.title": { en: "Indian papers and the wires", hi: "भारतीय अख़बार और वायर" },
  "insights.wire.body": { en: "How many of each paper's articles are on a story a wire also had, and how many nobody else had. Matched on headlines, so this is the same event, not copied text.", hi: "हर अख़बार के कितने लेख ऐसी खबर पर थे जो वायर पर भी थी, और कितने ऐसे जो किसी और के पास नहीं थे। हेडलाइन से मिलाया गया है, यानी एक ही घटना, कॉपी नहीं।" },
  "insights.wire.shared": { en: "Also on a wire", hi: "वायर पर भी" },
  "insights.wire.exclusive": { en: "Only them", hi: "सिर्फ़ इनके पास" },

  "insights.overlap.title": { en: "Most similar outlets", hi: "सबसे मिलते-जुलते सोर्स" },
  "insights.overlap.body": { en: "Stories both covered divided by stories either covered (Jaccard).", hi: "दोनों की साझा खबरें ÷ दोनों में से किसी की भी खबरें (Jaccard)।" },
  "insights.overlap.pair": { en: "Pair", hi: "जोड़ी" },
  "insights.overlap.shared": { en: "Shared", hi: "साझा" },
  "insights.overlap.similarity": { en: "Overlap", hi: "समानता" },

  "insights.mix.title": { en: "What each outlet covers", hi: "कौन क्या कवर करता है" },
  "insights.mix.body": { en: "Share of each outlet's articles per category. Biggest outlets only.", hi: "हर सोर्स के लेख, श्रेणी के हिसाब से। सिर्फ़ सबसे बड़े सोर्स।" },
  "insights.mix.outlet": { en: "Outlet", hi: "सोर्स" },

  "insights.rhythm.title": { en: "When news is published (IST)", hi: "खबरें कब छपती हैं (IST)" },
  "insights.rhythm.body": { en: "Articles by weekday and hour.", hi: "दिन और घंटे के हिसाब से लेख।" },
  "insights.rhythm.articles": { en: "articles", hi: "लेख" },
  "insights.dow.1": { en: "Mon", hi: "सोम" },
  "insights.dow.2": { en: "Tue", hi: "मंगल" },
  "insights.dow.3": { en: "Wed", hi: "बुध" },
  "insights.dow.4": { en: "Thu", hi: "गुरु" },
  "insights.dow.5": { en: "Fri", hi: "शुक्र" },
  "insights.dow.6": { en: "Sat", hi: "शनि" },
  "insights.dow.7": { en: "Sun", hi: "रवि" },

  "insights.scope.title": { en: "India vs world", hi: "भारत बनाम दुनिया" },
  "insights.scope.body": { en: "Share of new stories per section. Each story counted once.", hi: "हर सेक्शन में नई खबरों का हिस्सा। हर खबर एक बार गिनी गई।" },
  "insights.scope.stories": { en: "stories", hi: "खबरें" },

  "insights.health.title": { en: "Sources", hi: "सोर्स" },
  "insights.health.body": { en: "Every source we pull from. Quiet ones usually come back on their own.", hi: "हर सोर्स जिससे खबरें आती हैं। चुप सोर्स अक्सर खुद लौट आते हैं।" },
  "insights.health.source": { en: "Source", hi: "सोर्स" },
  "insights.health.status": { en: "Status", hi: "स्थिति" },
  "insights.health.articles": { en: "Articles", hi: "लेख" },
  "insights.health.lastArticle": { en: "Last article", hi: "आख़िरी लेख" },
  "insights.health.usableTime": { en: "Usable times", hi: "सही समय" },
  "insights.health.grounded": { en: "Grounded", hi: "सत्यापित" },
  "insights.health.words": { en: "Median words", hi: "औसत शब्द" },
  "insights.health.discovery": { en: "Found via", hi: "कैसे मिला" },
  "insights.status.ok": { en: "Healthy", hi: "ठीक" },
  "insights.status.quiet": { en: "Quiet", hi: "धीमा" },
  "insights.status.silent": { en: "Silent", hi: "चुप" },
  "insights.status.never": { en: "No articles", hi: "कोई लेख नहीं" },
  "insights.discovery.explicit": { en: "Feed URL", hi: "फ़ीड URL" },
  "insights.discovery.head-meta": { en: "Declared feed", hi: "घोषित फ़ीड" },
  "insights.discovery.common-path": { en: "Common path", hi: "आम पाथ" },
  "insights.discovery.sitemap": { en: "Sitemap", hi: "साइटमैप" },

  "insights.method.title": { en: "How this is measured", hi: "यह कैसे मापा गया" },
  "insights.method.body": { en: "Publish times come from the publishers. Missing ones, bare dates, times in the future and times more than a week old are left out. A story is a group of similar headlines from different outlets within 48 hours.", hi: "प्रकाशन समय पब्लिशर खुद देते हैं। जो समय नहीं है, सिर्फ़ तारीख़ है, भविष्य का है या हफ़्ते भर से पुराना है, उसे छोड़ दिया गया। एक खबर यानी 48 घंटे में अलग-अलग सोर्स की मिलती-जुलती हेडलाइनें।" },

  "site.title": { en: "Bharat Lens", hi: "भारत लेंस" },
  "site.tagline": { en: "News from India and the world, one card per story.", hi: "भारत और दुनिया की खबरें, हर खबर एक बार।" },
} as const satisfies Record<string, { en: string; hi: string }>;

export type UiStringKey = keyof typeof UI_STRINGS;

export function t(key: UiStringKey, lang: Lang): string {
  return UI_STRINGS[key][lang];
}
