-- Full-text search index for /search.
--
-- Not generated by drizzle-kit: it is an expression index over two columns, and
-- drizzle's schema builder has no way to express to_tsvector(). Apply it by hand
-- after db:push, or search falls back to a sequential scan over every article.
--
--   psql "$DATABASE_URL" -f drizzle/manual/0001_search_index.sql
--
-- The expression must match the one in searchArticles() exactly, or Postgres
-- will not use the index. 'english' is passed as a literal because to_tsvector
-- is only IMMUTABLE with an explicit config, and an expression index requires
-- immutability.

CREATE INDEX IF NOT EXISTS "articles_search_idx"
ON "articles" USING GIN (
  to_tsvector('english', "title" || ' ' || coalesce("excerpt", ''))
);
